### PR TITLE
Add Tides Controller and Relevant Tests

### LINKED ISSUE #13: Add Tides Controller and Tests
# Acceptance Criteria:

- [ ] There is <tt>TidesController.java</tt> file in the `src/main/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [ ] <tt>TidesController.java</tt> implements a class that implements an API endpoint that takes in the necessary
      parameters, calls the <tt>TidesQueryService</tt>, and returns the results.
- [ ] The file  <tt>TidesController.java</tt> file make appropriate use of the
      annotations `@Tag`, `@Operation` and `@Parameter` to document the API.
- [ ] The controller endpoint shows up on the Swagger UI page.
- [ ] There is a <tt>TidesControllerTests.java</tt> file in the `src/test/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [ ] The tests in <tt>TidesControllerTests</tt> provide 100% coverage of <tt>TidesController</tt> for both jacoco and pitest.

# Details

See the assignment description at https://ucsb-cs156.github.io/s24/lab/team01 for details.

### PR DESCRIPTION
**Pull request by Jumshim**
In this PR, we added an endpoint for `/api/tides/get` that can be used to get information about the tides within a date range of a particular station.

Note: Wait for the Tides Service PR to be merged before merging this one.

Dokku Dev Deployment for Tides: [http://team01-jumshim-dev.dokku-08.cs.ucsb.edu](http://team01-jumshim-dev.dokku-08.cs.ucsb.edu)
* `swagger-ui/index.html`: [http://team01-jumshim-dev.dokku-08.cs.ucsb.edu/swagger-ui/index.html](http://team01-jumshim-dev.dokku-08.cs.ucsb.edu/swagger-ui/index.html)

Closes #13

### CODE REVIEW

**Review by vaaniarora — APPROVED** [review]
LGTM

**Comment by rainakakani21** [comment]
lgtm!

**Review by rainakakani21 — APPROVED** [review]
lgtm!

**Review by niyati-m — APPROVED** [review]
LGTM

**Review by emilythai — APPROVED** [review]
LGTM!

**Review by charlene-patenaude — APPROVED** [review]
lgtm :)

**Pull request merged**
