### PR TITLE
Raina readme fixes

### PR DESCRIPTION
**Pull request by rainakakani21**
added my name and githubid to the readme

### CODE REVIEW

**Review by vaaniarora — APPROVED** [review]
lgtm!

**Review by niyati-m — APPROVED** [review]
lgtm

**Review by emilythai — APPROVED** [review]
LGTM!

**Review by charlene-patenaude — COMMENTED** [review]
lgtm :)

**Review by Jumshim — APPROVED** [review]
LGTM!

**Review by charlene-patenaude — APPROVED** [review]
lgtm :)

**Pull request merged**
