### PR TITLE
Niyati zipcode

### PR DESCRIPTION
**Pull request by niyati-m**
Finished ZipcodeService and Tests

### CODE REVIEW

**Review by Jumshim — APPROVED** [review]
LGTM!

**Review by rainakakani21 — APPROVED** [review]
lgtm

**Review by vaaniarora — APPROVED** [review]
lgtm :)

**Review by emilythai — APPROVED** [review]
LGTM!

**Review by charlene-patenaude — APPROVED** [review]
lgtm :)

**Pull request merged**
