### PR TITLE
jm - created Home controller and tests

### LINKED ISSUE #3: Customize Home Controller and Tests
## Acceptance criteria

- [ ] The Home Controller is updated with the names of the team members.
- [ ] The Home Controller Tests are updated with the names of the team members.

## Details

See the assignment description at https://ucsb-cs156.github.io/s24/lab/team01 for details.

### PR DESCRIPTION
**Pull request by Jumshim**
In this PR, we updated the information in the Home Controller to be accurate These changes included:
1) Adding all members of our team
2) Updating the github repository link

Closes #3

### CODE REVIEW

**Review by niyati-m — APPROVED** [review]
LGTM!

**Review by rainakakani21 — APPROVED** [review]
lgtm

**Review by emilythai — APPROVED** [review]
LGTM!

**Review by charlene-patenaude — APPROVED** [review]
lgtm :)

**Review by vaaniarora — APPROVED** [review]
lgtm!

**Pull request merged**
